// Bundled example document, shown when the app loads with no #v1: hash.
//
// Built BY HAND from trimwrit's own real data (read-only, not generated by
// any script) per the contract's "Producer mapping" section:
//   - .trimwrit/ledger.jsonl        (5 corrections, 3 promotions/gates)
//   - evals/results/latest.json    (3 graded cases)
//   - examples/CLAUDE.md            (3 promoted rule markers)
//
// Corrections: em-dash #0001, #0002; time-estimate #0003; decision-last
// #0004, #0005. All five were promoted, so all are "passed" and every gate
// they feed has a promotion record. Only corrections 0002, 0003 and 0005
// carry a case (per the ledger's "case" amends), so only those three gates
// have an outgoing edge to a case; a case's delta is positive in all three
// results, so all three cases and the rules they cite are "passed".
import type { PipelineDoc } from "./types";

export const exampleDoc: PipelineDoc = {
  v: 1,
  name: "examples/CLAUDE.md",
  generated_at: "2026-08-23T13:59:14-0500",
  roots: ["c0001", "c0002", "c0003", "c0004", "c0005"],
  stages: [
    {
      id: "c0001",
      kind: "correction",
      label: "em-dash #0001",
      status: "passed",
      meta: [
        { label: "date", value: "2026-08-23" },
        {
          label: "quote",
          value: "you used an em-dash again in that summary, I have told you this",
        },
      ],
      next: ["g-em-dash"],
    },
    {
      id: "c0002",
      kind: "correction",
      label: "em-dash #0002",
      status: "passed",
      meta: [
        { label: "date", value: "2026-08-23" },
        { label: "quote", value: "there are two em-dashes in the commit message you just wrote" },
      ],
      next: ["g-em-dash"],
    },
    {
      id: "c0003",
      kind: "correction",
      label: "time-estimate #0003",
      status: "passed",
      meta: [
        { label: "date", value: "2026-08-23" },
        { label: "quote", value: "don't estimate this in hours, I never asked for a timeline" },
      ],
      next: ["g-time-estimate"],
    },
    {
      id: "c0004",
      kind: "correction",
      label: "decision-last #0004",
      status: "passed",
      meta: [
        { label: "date", value: "2026-08-23" },
        { label: "quote", value: "the decision is buried in the middle again, I don't read long answers" },
      ],
      next: ["g-decision-last"],
    },
    {
      id: "c0005",
      kind: "correction",
      label: "decision-last #0005",
      status: "passed",
      meta: [
        { label: "date", value: "2026-08-23" },
        { label: "quote", value: "you gave me a menu with no pick, that hands the work back to me" },
      ],
      next: ["g-decision-last"],
    },
    {
      id: "g-em-dash",
      kind: "gate",
      label: "counter 2/2",
      status: "passed",
      meta: [
        {
          label: "consequence",
          value:
            "a launch post went out with three em-dashes and read as machine written to the audience it was aimed at",
        },
      ],
      next: ["k0002-no-em-dash-anywhere"],
    },
    {
      id: "g-time-estimate",
      kind: "gate",
      label: "important",
      status: "passed",
      meta: [
        {
          label: "consequence",
          value: "an estimate in hours was quoted back inside a client thread and was wrong by 3x",
        },
      ],
      next: ["k0003-no-time-estimate"],
    },
    {
      id: "g-decision-last",
      kind: "gate",
      label: "counter 2/2",
      status: "passed",
      meta: [
        {
          label: "consequence",
          value:
            "a long answer buried its recommendation in the middle and the reader stopped before reaching it",
        },
      ],
      next: ["k0005-decision-last-and-short"],
    },
    {
      id: "k0002-no-em-dash-anywhere",
      kind: "case",
      label: "0002-no-em-dash-anywhere",
      status: "passed",
      meta: [
        { label: "graders", value: "1" },
        { label: "with", value: "1.00" },
        { label: "without", value: "0.00" },
        { label: "delta", value: "1.00" },
      ],
      next: ["R0002"],
    },
    {
      id: "k0003-no-time-estimate",
      kind: "case",
      label: "0003-no-time-estimate",
      status: "passed",
      meta: [
        { label: "graders", value: "3" },
        { label: "with", value: "1.00" },
        { label: "without", value: "0.67" },
        { label: "delta", value: "0.33" },
      ],
      next: ["R0003"],
    },
    {
      id: "k0005-decision-last-and-short",
      kind: "case",
      label: "0005-decision-last-and-short",
      status: "passed",
      meta: [
        { label: "graders", value: "1" },
        { label: "with", value: "1.00" },
        { label: "without", value: "0.33" },
        { label: "delta", value: "0.67" },
      ],
      next: ["R0005"],
    },
    {
      id: "R0002",
      kind: "rule",
      label: "R0002",
      status: "passed",
      meta: [
        {
          label: "incident",
          value:
            "a launch post went out with three em-dashes and read as machine written to the audience it was aimed at",
        },
        { label: "target", value: "examples/CLAUDE.md" },
      ],
      next: [],
    },
    {
      id: "R0003",
      kind: "rule",
      label: "R0003",
      status: "passed",
      meta: [
        {
          label: "incident",
          value: "an estimate in hours was quoted back inside a client thread and was wrong by 3x",
        },
        { label: "target", value: "examples/CLAUDE.md" },
      ],
      next: [],
    },
    {
      id: "R0005",
      kind: "rule",
      label: "R0005",
      status: "passed",
      meta: [
        {
          label: "incident",
          value:
            "a long answer buried its recommendation in the middle and the reader stopped before reaching it",
        },
        { label: "target", value: "examples/CLAUDE.md" },
      ],
      next: [],
    },
  ],
};
